import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { INVENTORY } from '../packages/shared-rbac/src/inventory.ts';
import { canonicalKeys } from '../packages/shared-rbac/src/manifest.ts';

const keys = INVENTORY.flatMap((m) => canonicalKeys(m.statement)).sort();
const union = keys.map((k) => `  | '${k}'`).join('\n');
const arr = keys.map((k) => `  '${k}',`).join('\n');
const body = `// GENERATED by pnpm gen:rbac — do not edit by hand.
export type PermissionKey =
${union};

export const ALL_PERMISSIONS: readonly PermissionKey[] = [
${arr}
];
`;
writeFileSync(
  resolve(import.meta.dirname, '../packages/shared-rbac/src/generated/permission-keys.ts'),
  body,
);
console.log(`wrote ${keys.length} permission keys`);
